### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by booherbg** [Seed-to-Feed/seedtofeed#63]
- "Not a Member" should be consistent with "Login" subtitle
  - Seed to Feed logo on the right feels off (why are they on different lines? Why are both logos the same but go different places?)
  - Shrink the navbar so it isnt taking up so much space (left logo smaller?)
  - Add some verbage thats like "Welcome to the Blah Blah app"

**Comment by wells19d** [comment]
This has been corrected up to the registration. Right now the radio buttons have an error that is being addressed.

**Comment by Steve-Burket** [comment]
Radio buttons work now
