### ISSUE TITLE
Navbar: Make navbar consistent (one horizontal line of text only, not multiple lines, etc)

### ISSUE THREAD

**Issue by booherbg** [Seed-to-Feed/seedtofeed#70]

**Comment by wells19d** [comment]
Updated the Nav bar. 

Adjusted the stamp logo to offset/overlap to reflect the logo on the info page.

Changed the title "Tracker" to balance the bar. I think it still needs more work, doesn't quite look right.

Changed the appearance of the nav buttons to a drop down menu list. Changed the logout button to a onClick function inside a link. Tested and works great. The menu drop down gives an appearance of a pop up and offsets on the nav bar (on purpose). This will eliminate the need of the logout button component. All the links now match.

Removed (commented out for now) un-needed links that don't work, pointing to incorrect locations, or not setup.
