### ISSUE TITLE
In general, consider adding user feedback when actions are taken (new field created successfully, deleted field, edited field, added buyer, etc)

### ISSUE THREAD

**Issue by booherbg** [Seed-to-Feed/seedtofeed#78]
Can use sweet alerts, or a simple global alert, bootstrap / material alert component, etc.

**Comment by DavidVinson** [comment]
Workflow: CRUD Action
Add Field: POST/field table, POST/user_field table, POST/field_transactions table
Add Contract: POST/contract table, POST/field_transactions table
Add NIR: POST/NIR table, POST/field_transactions table
ADD Transaction: POST/field_transaction
EDIT Field: UPDATE/field_table, POST/field_transactions table
EDIT Contract: UPDATE/contract table, POST/field_transactions table
EDIT NIR: UPDATE/NIR table, POST/field_transactions table
EDIT Transactions: UPDATE/field_transactions table

**Comment by DavidVinson** [comment]
more along the lines of a material alert banner at the top of the page.
